module.exports = {
  0: [
    {
      code: "CAD-L",
      location: "Punit kumar",
      end: "09:25",
      start: "08:30",
    },
    {
      location: "Prof Jaideep",
      end: "10:20",
      start: "09:25",
      code: "DOM-L",
    },
    {
      start: "10:40",
      end: "11:35",
      code: "MD-L",
      location: "Prof Satnam Singh",
    },
    {
      end: "15:35",
      code: "NE-L",
      location: "Prof Nirmal Kant",
      start: "14:40",
    },
    {
      end: "16:30",
      start: "15:35",
      code: "TPE-L",
      location: "Neeraj Mehla",
    },
    {
      code: "PT-L",
      location: "Prof Hari Singh",
      end: "17:25",
      start: "16:30",
    },
  ],
  1: [
    {
      start: "08:30",
      code: "TPE-L",
      end: "09:25",
      location: "Neeraj Mehla",
    },
    {
      start: "09:25",
      code: "DOM-L",
      location: "Prof Jaideep",
      end: "10:20",
    },
    {
      end: "13:25",
      start: "10:40",
      code: "CAD(P)",
      location: "Indu Saini",
    },
    {
      start: "14:40",
      code: "NE-L",
      location: "Prof Nirmal Kant",
      end: "15:35",
    },
    {
      code: "TPE-L",
      location: "Neeraj Mehla",
      start: "15:35",
      end: "16:30",
    },
    {
      location: "Punit Kumar",
      end: "17:25",
      start: "16:30",
      code: "CAD-L",
    },
  ],
  2: [
    {
      code: "NM(P)",
      end: "10:20",
      location: "Rajiv Verma",
      start: "08:30",
    },
    {
      start: "10:40",
      location: "S SINGHAL",
      code: "DOM-T",
      end: "11:35",
    },
    // {
    //   code: "NE-L",
    //   start: "11:35",
    //   end: "12:30",
    //   location: "Prof Nirmal Kant",
    // },
    {
      code: "SOM-L",
      start: "12:30",
      end: "13:25",
      location: "Prof Mahesh Gupta",
    },
    {
      start: "14:40",
      end: "15:35",
      location: "Prof Jaideep",
      code: "DOM-L",
    },
    {
      end: "16:30",
      code: "PT-L",
      location: "Prof Hari Singh",
      start: "15:35",
    },
  ],
  3: [
    {
      start: "08:30",
      end: "09:25",
      code: "PT-L",
      location: "Prof Hari Singh",
    },
    {
      start: "09:25",
      end: "10:20",
      location: "Prof Mahesh Gupta",
      code: "SOM-L",
    },
    {
      end: "11:35",
      code: "NE-L",
      location: "Prof Nirmal Kant",
      start: "10:40",
    },
    {
      start: "11:35",
      code: "TPE-L",
      location: "Prof Neeraj Mehla",
      end: "12:30",
    },
    {
      location: "Prof Mahesh Gupta",
      start: "13:45",
      code: "SOM-T",
      end: "14:40",
    },
    {
      location: "Prof Arvind",
      code: "TOM(P)",
      end: "16:30",
      start: "14:40",
    },
  ],
  4: [
    {
      code: "MD-T",
      location: "Prof Satnam Singh",
      end: "11:35",
      start: "08:30",
    },
    {
      code: "SOM-T",
      location: "Prof Mahesh Gupta",
      start: "11:35",
      end: "12:30",
    },
    {
      start: "13:45",
      code: "PT-T",
      location: "Prof Hari Singh",
      end: "14:40",
    },
    {
      end: "16:30",
      start: "14:40",
      code: "PT(P)",
      location: "Prof Hari Singh",
    },
  ],
};
