export default {
  "CAD(P)": "CAD LAB",
  "CAD-L": "CAD Elective",
  "DOM-L": "DOM Lecture",
  "DOM-T": "DOM Tutorial",
  "MD-L": "Machine Design Lecture",
  "MD-T": "Machine Design",
  "NE-L": "Nuclear Engineering Lecture",
  "NM(P)": "Numerical Methods Lab",
  "PT(P)": "Production Technology Lab",
  "PT-L": "Production Technology Lecture",
  "PT-T": "Production Technology Tut",
  "SOM-L": "Strength of Materials Lecture",
  "SOM-T": "Strength of Materials Tut",
  "TOM(P)": "Theory of Machines Lab",
  "TPE-L": "Thermal Power lecture",
};
